export const recipes = [
  {
    id: 1,
    category: 'Frequent',
    recipes: [
      {
        id: 1,
        name: 'Idly',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/idli.png'),
      },
      {
        id: 2,
        name: 'Medu Vada',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/vada.png'),
      },
      {
        id: 3,
        name: 'Dosa',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/dosa.png'),
      },
    ],
  },
  {
    id: 2,
    category: 'All Recipes',
    recipes: [
      {
        id: 1,
        name: 'Idly',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/idli.png'),
      },
      {
        id: 2,
        name: 'Medu Vada',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/vada.png'),
      },
      {
        id: 3,
        name: 'Dosa',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/dosa.png'),
      },
    ],
  },
  {
    id: 3,
    category: 'Favorite',
    recipes: [
      {
        id: 1,
        name: 'Idly',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/idli.png'),
      },
      {
        id: 2,
        name: 'Medu Vada',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/vada.png'),
      },
      {
        id: 3,
        name: 'Dosa',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/dosa.png'),
      },
    ],
  },
  {
    id: 4,
    category: 'Most Wanted',
    recipes: [
      {
        id: 1,
        name: 'Idly',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/idli.png'),
      },
      {
        id: 2,
        name: 'Medu Vada',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/vada.png'),
      },
      {
        id: 3,
        name: 'Dosa',
        R: '40%',
        W: '20%',
        D: '10%',
        image: require('../../assets/images/dosa.png'),
      },
    ],
  },
];
